"""initial_schema

Revision ID: 9391613f4c07
Revises: 
Create Date: 2026-08-19 23:01:13.732983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9391613f4c07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('poll_registry','extract_changes','scan_repo','generate_patch','open_pr')", name='ck_jobs_type'),
    sa.CheckConstraint("status IN ('queued','running','done','failed')", name='ck_jobs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_status_run_after', 'jobs', ['status', 'run_after'], unique=False, postgresql_where="status = 'queued'")
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ecosystem', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.CheckConstraint("ecosystem IN ('npm','pypi')", name='ck_packages_ecosystem'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecosystem', 'name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('github_login', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_table('installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('installed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('User','Organization')", name='ck_installations_account_type'),
    sa.ForeignKeyConstraint(['installed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_installation_id')
    )
    op.create_table('package_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('changelog_raw', sa.Text(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scanned_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'version')
    )
    op.create_table('detected_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_version_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('symbol_old', sa.Text(), nullable=False),
    sa.Column('symbol_new', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.REAL(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("change_type IN ('signature_change','removed','renamed','deprecated','behavior_change')", name='ck_detected_changes_type'),
    sa.ForeignKeyConstraint(['package_version_id'], ['package_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repo_id')
    )
    op.create_table('code_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('detected_change_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','patched','skipped','failed')", name='ck_code_usages_status'),
    sa.ForeignKeyConstraint(['detected_change_id'], ['detected_changes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('package_version_id', sa.UUID(), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('github_pr_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('patch_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('opened_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open','merged','closed')", name='ck_pull_requests_status'),
    sa.ForeignKeyConstraint(['package_version_id'], ['package_versions.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('current_version', sa.Text(), nullable=False),
    sa.Column('manifest_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'package_id')
    )
    op.create_table('patches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_usage_id', sa.UUID(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('llm_provider', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('human_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_usage_id'], ['code_usages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patch_id', sa.UUID(), nullable=False),
    sa.Column('applies_cleanly', sa.Boolean(), nullable=False),
    sa.Column('parses', sa.Boolean(), nullable=False),
    sa.Column('typechecks', sa.Boolean(), nullable=True),
    sa.Column('tests_pass', sa.Boolean(), nullable=True),
    sa.Column('scope_ok', sa.Boolean(), nullable=False),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_runs')
    op.drop_table('patches')
    op.drop_table('repo_packages')
    op.drop_table('pull_requests')
    op.drop_table('code_usages')
    op.drop_table('repos')
    op.drop_table('detected_changes')
    op.drop_table('package_versions')
    op.drop_table('installations')
    op.drop_table('users')
    op.drop_table('packages')
    op.drop_index('idx_jobs_status_run_after', table_name='jobs', postgresql_where="status = 'queued'")
    op.drop_table('jobs')
    # ### end Alembic commands ###
