"use client";

import React from "react";
import SpotlightCard from "@/components/ui/SpotlightCard";
import KineticHeader from "@/components/ui/KineticHeader";
import CyberGridBackground from "@/components/ui/CyberGridBackground";

const PROVIDERS = [
  { id: "gemini", label: "Gemini 2.0 Flash", note: "Free tier · default", available: true },
  { id: "claude", label: "Claude Sonnet", note: "Requires ANTHROPIC_API_KEY", available: false },
];

export default function SettingsPage() {
  return (
    <div className="flex flex-col gap-10 relative z-10">
      <CyberGridBackground />

      <KineticHeader
        badge="CONFIGURATION"
        title="Settings & Integrations"
        subtitle="LLM provider routing, model selection, and event notification webhooks."
      />

      {/* LLM Provider */}
      <section className="flex flex-col gap-4">
        <h2 className="font-mono font-semibold text-base text-white tracking-tight">
          LLM Provider Routing
        </h2>
        <p className="font-sans text-sm text-[#A1A1AA]">
          All patches and failure classifications generated by Telex are cryptographically logged with provider and model metadata.
        </p>
        <div className="flex flex-col gap-3">
          {PROVIDERS.map((p) => (
            <SpotlightCard
              key={p.id}
              className={`p-4 ${p.available ? "hover:border-white/40" : "opacity-50 cursor-not-allowed"}`}
              enableTilt={p.available}
            >
              <label className="flex items-center justify-between cursor-pointer w-full">
                <div className="flex items-center gap-3">
                  <input
                    type="radio"
                    name="provider"
                    value={p.id}
                    defaultChecked={p.id === "gemini"}
                    disabled={!p.available}
                    className="accent-white w-4 h-4 cursor-pointer"
                  />
                  <div>
                    <div className="font-mono text-sm text-white">{p.label}</div>
                    <div className="font-mono text-[11px] text-[#71717A]">{p.note}</div>
                  </div>
                </div>
                {!p.available && (
                  <span className="font-mono text-[10px] tracking-widest border border-white/20 rounded px-2 py-0.5 text-[#71717A]">
                    COMING SOON
                  </span>
                )}
              </label>
            </SpotlightCard>
          ))}
        </div>
      </section>

      {/* Notifications */}
      <section className="flex flex-col gap-4">
        <h2 className="font-mono font-semibold text-base text-white tracking-tight">
          Webhook Notifications
        </h2>
        <div className="flex flex-col gap-3">
          {[
            { label: "PR opened", detail: "When Telex opens a new patch PR after verification" },
            { label: "PR merged", detail: "When a self-healed patch PR is merged" },
            { label: "Scan complete", detail: "After each automated repository AST scan" },
          ].map((n) => (
            <SpotlightCard key={n.label} className="p-4" enableTilt={false}>
              <label className="flex items-center justify-between cursor-pointer w-full">
                <div>
                  <div className="font-mono text-sm text-white">{n.label}</div>
                  <div className="font-mono text-[11px] text-[#71717A]">{n.detail}</div>
                </div>
                <input
                  type="checkbox"
                  defaultChecked
                  className="accent-white w-4 h-4 cursor-pointer"
                />
              </label>
            </SpotlightCard>
          ))}
        </div>
      </section>
    </div>
  );
}
