import type { Metadata } from "next";

export const metadata: Metadata = { title: "Dashboard — Settings" };

const PROVIDERS = [
  { id: "gemini", label: "Gemini 2.0 Flash", note: "Free tier · default", available: true },
  { id: "claude", label: "Claude Sonnet", note: "Requires ANTHROPIC_API_KEY", available: false },
];

export default function SettingsPage() {
  return (
    <div className="flex flex-col gap-10">
      <div>
        <h1
          className="font-mono font-bold text-2xl text-text"
          style={{ letterSpacing: "-0.02em" }}
        >
          Settings
        </h1>
        <p className="font-sans text-sm mt-1" style={{ color: "var(--muted)" }}>
          LLM provider and notification preferences.
        </p>
      </div>

      {/* LLM Provider */}
      <section className="flex flex-col gap-4">
        <h2 className="font-mono font-semibold text-base text-text">
          LLM Provider
        </h2>
        <p className="font-sans text-sm" style={{ color: "var(--muted)" }}>
          All patches generated by Telex are logged with the provider and model
          that produced them. You can switch providers without losing history.
        </p>
        <div className="flex flex-col gap-3">
          {PROVIDERS.map((p) => (
            <label
              key={p.id}
              className={[
                "flex items-center justify-between rounded-lg p-4 cursor-pointer transition-all",
                p.available ? "hover:border-patch/40" : "opacity-50 cursor-not-allowed",
              ].join(" ")}
              style={{
                background: "var(--panel)",
                border: "1px solid rgba(139,144,153,0.15)",
              }}
            >
              <div className="flex items-center gap-3">
                <input
                  type="radio"
                  name="provider"
                  value={p.id}
                  defaultChecked={p.id === "gemini"}
                  disabled={!p.available}
                  className="accent-[#4FD1C5]"
                />
                <div>
                  <div className="font-mono text-sm text-text">{p.label}</div>
                  <div className="font-mono text-[11px] text-muted">{p.note}</div>
                </div>
              </div>
              {!p.available && (
                <span
                  className="font-mono text-[10px] tracking-widest border rounded px-2 py-0.5"
                  style={{ color: "var(--muted)", borderColor: "rgba(139,144,153,0.3)" }}
                >
                  COMING SOON
                </span>
              )}
            </label>
          ))}
        </div>
      </section>

      {/* Notifications */}
      <section className="flex flex-col gap-4">
        <h2 className="font-mono font-semibold text-base text-text">
          Notifications
        </h2>
        <div className="flex flex-col gap-3">
          {[
            { label: "PR opened", detail: "When Telex opens a new patch PR" },
            { label: "PR merged", detail: "When a patch PR is merged" },
            { label: "Scan complete", detail: "After each repo scan finishes" },
          ].map((n) => (
            <label
              key={n.label}
              className="flex items-center justify-between rounded-lg p-4 cursor-pointer"
              style={{
                background: "var(--panel)",
                border: "1px solid rgba(139,144,153,0.12)",
              }}
            >
              <div>
                <div className="font-mono text-sm text-text">{n.label}</div>
                <div className="font-mono text-[11px] text-muted">{n.detail}</div>
              </div>
              <input
                type="checkbox"
                defaultChecked
                className="accent-[#4FD1C5] w-4 h-4"
              />
            </label>
          ))}
        </div>
      </section>
    </div>
  );
}
